spring:
  datasource:
    url: jdbc:mysql://192.168.221.132:3306/tensquare_article?useUnicode=true&characterEncoding=utf8&timeZone=HongKong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  data:
    mongodb:
      host: 192.168.221.132
      database: commentdb
  redis:
    host: 192.168.221.132
    port: 6379
  application:
    name: tensquare-article
server:
  port: 10001
mybatis:
  type-aliases-package: com.demo.tensquare.pojo
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.demo.tensquare.dao: debug
