server:
  port: 10002
spring:
  application:
    name: tensquare-notice
  datasource:
    url: mysql://192.168.221.132:3306/tensquare_notice?useUnicode=true&characterEncoding=utf8&timeZone=HongKong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.demo.tensquare.pojo
logging:
  level:
    com.demo.tensquare.dao: debug
